export const categories = [
    {
        id: 1,
        collection_name: 'Electronics',
        photo: '/assets/computer.png',
        desc: 'Shop laptops, desktops, monitors, tablets, PC gaming, hard drives and storage, accessories and more..',
        category: 'electronics',
    },
    {
        id: 2,
        collection_name: 'Beauty Picks',
        photo: '/assets/beauty.png',
        desc: 'Discover our beauty selection and shop beauty lipsticks, clone, beauty accessories and more..',
        category: 'beauty picks',
    },
    {
        id: 3,
        collection_name: 'Fashion',
        photo: '/assets/pp4.png',
        desc: 'Discover our fashion collection and shop clothes, shoes, bags, other fashion accessories and more..',
        category: 'fashion',
    },
    {
        id: 4,
        collection_name: 'Health & Household',
        photo: '/assets/pp8.png',
        desc: 'Refresh your household by shopping household essentials, health collection and more..',
        category: 'health & household',
    },
];


export const collectionProductSlider = [
    {
        id: 1,
        product_img: '/assets/p6.png',
        product_name: 'JBL T460BT Black Earbud',
        rating: 5,
        reviews: '1,245',
        product_price_original: 250,
        product_price_discount: 125,
        category: 'electronics',
    },
    {
        id: 2,
        product_img: '/assets/p3.png',
        product_name: 'LG Meridian Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
    },
    {
        id: 3,
        product_img: '/assets/pp15.png',
        product_name: 'RealmeOppA5s | Andriod Smart Phone',
        rating: 3,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
    },
    {
        id: 4,
        product_img: '/assets/pp1.png',
        product_name: 'Dark Blue Sport Sneaker',
        rating: 5,
        reviews: '1,105',
        product_price_original: 120,
        product_price_discount: 105,
        category: 'fashion',
    },
    {
        id: 5,
        product_img: '/assets/pp2.png',
        product_name: 'Dark Brown Ladder Shoe',
        rating: 4,
        reviews: '1,105',
        product_price_original: 130,
        product_price_discount: 105,
        category: 'fashion',
    },
    {
        id: 6,
        product_img: '/assets/pp3.png',
        product_name: 'Gray & White Long Sleeve T-Shirt',
        rating: 4,
        reviews: '105',
        product_price_original: 230,
        product_price_discount: 105,
        category: 'fashion',
    },
    {
        id: 7,
        product_img: '/assets/pp4.png',
        product_name: 'Brown Long Sleeve Ladder Jacket',
        rating: 5,
        reviews: '1,005',
        product_price_original: 230,
        product_price_discount: 105,
        category: 'fashion',
    },
    {
        id: 8,
        product_img: '/assets/pp14.png',
        product_name: 'Clear Glass Bottle With Yellow Liquid',
        rating: 5,
        reviews: '1,005',
        product_price_original: 130,
        product_price_discount: 105,
        category: 'beauty picks',
    },
    {
        id: 9,
        product_img: '/assets/pp16.png',
        product_name: 'White and Gold Container Body Oil',
        rating: 4,
        reviews: '1,005',
        product_price_original: 110,
        product_price_discount: 98,
        category: 'beauty picks',
    },
    {
        id: 10,
        product_img: '/assets/pp10.png',
        product_name: 'White Labeled Clear Plastic Bottle',
        rating: 4,
        reviews: '1,005',
        product_price_original: 110,
        product_price_discount: 98,
        category: 'beauty picks',
    },
    {
        id: 11,
        product_img: '/assets/pp9.png',
        product_name: 'Keener All Wood Round Dining Table',
        rating: 4,
        reviews: '1,005',
        product_price_original: 110,
        product_price_discount: 98,
        category: 'health & household',
    },
    {
        id: 12,
        product_img: '/assets/pp8.png',
        product_name: 'Classique Wood Chair Cane Backrest',
        rating: 4,
        reviews: '1,005',
        product_price_original: 110,
        product_price_discount: 98,
        category: 'health & household',
    },
    {
        id: 13,
        product_img: '/assets/pp12.png',
        product_name: 'Modern Wooden Parametric Petal Chair',
        rating: 4,
        reviews: '1,005',
        product_price_original: 110,
        product_price_discount: 98,
        category: 'health & household',
    },
]



export const products = [
    {
        id: 1,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        // product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed', 'lastMinute']
    },
    {
        id: 2,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling', 'recentViewed', 'lastMinute']
    },
    {
        id: 3,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed']
    },
    {
        id: 4,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed', 'lastMinute']
    },
    {
        id: 5,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed']
    },
    {
        id: 6,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling', 'lastMinute']
    },
    {
        id: 7,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured']
    },
    {
        id: 8,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', , 'lastMinute']
    },
    {
        id: 9,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling', 'recentViewed', 'lastMinute']
    },
    {
        id: 10,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed']
    },
    {
        id: 11,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed']
    },
    {
        id: 12,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['featured', 'recentViewed']
    },
    {
        id: 13,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling']
    },
    {
        id: 14,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling', 'recentViewed']
    },
    {
        id: 15,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling', 'recentViewed']
    },
    {
        id: 16,
        product_img: '/assets/p11.png',
        product_name: 'Wireless Black Earbud',
        rating: 4,
        reviews: '1,245',
        product_price_original: 220,
        product_price_discount: 115,
        category: 'electronics',
        brand: 'araimo',
        tag: 'best seller',
        level: ['topSelling']
    },
    
];

const lastMinuteDeal = [];